export enum actionType {
  FILTRAR_PERSONAJES = "FILTRAR_PERSONAJES",
  FILTRAR_PERSONAJES_EXITO = "FILTRAR_PERSONAJES_EXITO",
  FILTRAR_PERSONAJES_ERROR = "FILTRAR_PERSONAJES_ERROR",
  AGREGAR_FAVORITO = "AGREGAR_FAVORITO",
  ELIMINAR_FAVORITO = "ELIMINAR_FAVORITO",
}
